#!/usr/bin/env sh
# Git hook file
# See: https://git-scm.com/docs/githooks
################# SETUP #################
export PATH="node_modules/.bin:${PATH}" #
set -o errexit -o xtrace -o nounset     #
#########################################

pnpm run check
cargo fmt --check
