name: Update Cache

on:
  push:
    branches:
      - main
    paths:
      - Cargo.lock
      - pnpm-lock.yaml

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  update-cache:
    name: Update Cache

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: pnpm

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
